version: "3.7"
services:
  exchange:
    build: ./dockerfiles/go
    ports:
      - "1323:1323"
  
  mongodb:
    build: ./dockerfiles/mongodb
    restart: always
    ports:
      - "27017-27019:27017-27019"