version: "3.7"
services:
  exchange:
    build: ./
    ports:
      - "1323:1323"
  
  mongodb:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017-27019:27017-27019"